l = []

l.append(-113)
l.append(-113)
l.append(-113)
l.append(-113)
l.append(-113)
l.append(-113)
l.append(-113)
l.append(-113)
l.append(-113)
l.append(-113)

print(f"Slot 0 contains a {l[0]}")
print(f"Slot 1 contains a {l[1]}")
print(f"Slot 2 contains a {l[2]}")
print(f"Slot 3 contains a {l[3]}")
print(f"Slot 4 contains a {l[4]}")
print(f"Slot 5 contains a {l[5]}")
print(f"Slot 6 contains a {l[6]}")
print(f"Slot 7 contains a {l[7]}")
print(f"Slot 8 contains a {l[8]}")
print(f"Slot 9 contains a {l[9]}")
